### ISSUE TITLE
KafkaProducer can't resolve future metadata in some scenarios

### ISSUE THREAD

**Issue by jar349** [dpkp/kafka-python#1337]
I've written my own test script for the docker-compose.yml in this repository: https://gist.github.com/jar349/c1fa8d84bab92c8a6c4f427ffa27a4a0 

I've also dockerized this script so that I can run it as a Job in kubernetes: https://hub.docker.com/r/jar349/kafka-test/

When I run Kafka in docker-compose and then run my script on the host, everything works.
When I run Kafka in kubernetes (minikube) and then my docker image as a Job, everything works.

If I try to link my docker container to the docker-compose cluster, the producer times out getting metadata
If I try to run my script against the exposed kafka service in kubernetes, the producer times out getting metadata

```
docker run --rm -a STDOUT -a STDERR --network="kafkadocker_default" --link kafkadocker_kafka_1 -e "KAFKA_HOST=kafkadocker_kafka_1" -e "KAFKA_PORT=9092" jar349/kafka-test:latest
Traceback (most recent call last):
  File "/opt/test/test.py", line 82, in <module>
    main()
  File "/opt/test/test.py", line 77, in main
    message_info = tester.produce()
  File "/opt/test/test.py", line 48, in produce
    metadata = future_metadata.get(timeout=10)
  File "/opt/test/venv/lib/python2.7/site-packages/kafka/producer/future.py", line 62, in get
    "Timeout after waiting for %s secs." % timeout)
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Timeout after waiting for 10 secs.
```
Here's my docker-compose.yml:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG, authorizerAppender
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Here's my kubernetes Job:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-test
spec:
  template:
    spec:
      containers:
      - name: kafka-test
        image: jar349/kafka-test:latest
        env:
        - name: KAFKA_HOST
          value: "kafka-kafka"
        - name: KAFKA_PORT
          value: "9092"
      restartPolicy: Never
  backoffLimit: 4
```
Naturally, my first thought was that something was wrong with my networking.  But in each failure case, I was able to telnet to the kafka server on port 9092 (I saw the error log in the kafka server).

So in the case of not connecting to docker-compose from my docker container, I ran:
```
docker run --rm -it --network="kafkadocker_default" --link "kafkadocker_kafka_1:kafka" -e "KAFKA_HOST=kafka" -e "KAFKA_PORT=9092" jar349/kafka-test:latest /bin/bash
```
and inside of the docker container, I can ping kafka and also telnet to kafka on 9092:
```
# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:14:00:04  
          inet addr:172.20.0.4  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7664 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4680 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10770957 (10.2 MiB)  TX bytes:255961 (249.9 KiB)

# ping -c 2 kafka
PING kafka (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: icmp_seq=0 ttl=64 time=0.137 ms
64 bytes from 172.20.0.3: icmp_seq=1 ttl=64 time=0.153 ms
--- kafka ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.137/0.145/0.153/0.000 ms

# telnet kafka 9092
Trying 172.20.0.3...
Connected to kafka.
Escape character is '^]'.
HELLO
Connection closed by foreign host.

--- and in the kafka server log ---

WARN Unexpected error from /172.20.0.4; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1212501068 larger than 104857600)
```

In the case where I try to run my script against an exposed kafka service, I can telnet there too but my script gets the timeout error shown above.
