### ISSUE TITLE
Working with multiple Kafka: Invalid file object: None

### ISSUE THREAD

**Issue by azzamsa** [dpkp/kafka-python#2223]
Hi.

I am trying to use `kafka-python` with multiple Kafka and multiple zookeeper.

Here is my Kafka:

|ID  | Address    |
|----|------------|
|1 👑| 10.10.10.10|
|2   | 20.20.20.20|
|3   | 30.30.30.30|

and the code:

``` python
broker = ["10.10.10.10:9092", "20.20.20.20:9092", "30.30.30.30:9092"]

producer = KafkaProducer(
        bootstrap_servers=brokers,
        value_serializer=lambda m: json.dumps(m).encode("utf-8"),
    )
```

It went well, until I simulate if any bad things happen. Such what if one of the Kafka down. So I shut down one of them:

|ID  | Address    |
|----|------------|
|1 👑| 10.10.10.10|
|2   | 20.20.20.20|

Using the same code as above, **I got `Invalid file object: None`**.
To solve the error. I need to remove stopped node from `bootstrap_servers`:

``` diff
-broker = ["10.10.10.10:9092", "20.20.20.20:9092", "30.30.30.30:9092"]
+broker = ["10.10.10.10:9092", "20.20.20.20:9092"]

producer = KafkaProducer(
```

**Is this expected behavior?**

Quoting from [confluent
doc](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_bootstrap.servers):

> Since these servers are just used for the initial connection to discover the
> full cluster membership (which may change dynamically), this list need not
> contain the full set of servers (you may want more than one, though, in case a
> server is down).

I think passing more than one host address to `bootstrap_server` is OK if we
have multiple Kafka.

I see Kafka CLI still works even the `--bootstrap-server` contains a stooped
node: (Note that 30.30.30.30 is down)

``` bash
$ # describe topic
$ docker run --rm confluentinc/cp-kafka:6.1.1 kafka-topics --describe --topic foo --bootstrap-server 30.30.30.30:9092,10.10.10.10:9092
Topic: domaindata       PartitionCount: 1       ReplicationFactor: 3    Configs:
        Topic: domaindata       Partition: 0    Leader: 2       Replicas: 3,2,1
        Isr: 2,1
        
$ # produce content to topic
$ docker run --rm confluentinc/cp-kafka:6.1.1 kafka-console-producer  --topic foo --bootstrap-server 30.30.30.30:9092,10.10.10.10:9092
>^C
```

---

```
# requirements.txt
kafka-python==2.0.2
```

```yaml
# one of node configuration

version: '3'
services:
  zoo1:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zoo2
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 10.10.10.10:2888:3888;20.20.20.20:2888:3888;0.0.0.0:2888:3888
  kafka1:
    image: confluentinc/cp-kafka:6.1.1
    hostname: kafka2
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER_CONNECT: 10.10.10.10:2181,20.20.20.20:2181,30.30.30.30:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://30.30.30.30:9092
```
